config/routes.rb
Rails.application.routes.draw do
  
  root "home#welcome"

  devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'sign_up' }
  
  resources :users   
  
  resources :quizzes do
    resources :questions  do
      resources :options
    end
  end

  # API V1
  namespace :api, defaults: {format: :json}  do
    namespace :v1 do      
      post 'login', to: 'sessions#create'
      post 'logout', to: 'sessions#destroy'      
      resources :quizzes, only: [:index, :show]      
      resources :quiz_user_answers, only: [:create]      
    end
  end

  

  
end

app/controllers/api/v1/quizzes_controller.rb
class Api::V1::QuizzesController < Api::V1::AppController

  before_action :authenticate_with_token!

  before_action :set_quiz, only: [:show, :edit, :update, :destroy]

  def index
    @quizzes = Quiz.all.order(id: :asc)
    render json: { quizzes: @quizzes }    
  end

  def show
    @quiz = Quiz.find(params[:id])    
    @questions = @quiz.questions
    render json: { quiz: @quiz,questions:  @questions } 
  end

  private    

    def set_quiz
      @quiz = Quiz.find(params[:id])
    end

    def quiz_params      
      params.require(:quiz).permit(:name, :description)      
    end

end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController

  before_action :set_quiz, only: [:show, :edit, :update, :destroy]

  def index
    @quizzes = Quiz.all.order(id: :asc)
  end

  def show
    @quiz = Quiz.find(params[:id])    
    @questions = @quiz.questions
  end

  def new
    @quiz = Quiz.new(params[:quiz])    
  end

  def edit
    # @quiz = Quiz.find(params[:id])    
  end

  def create
    @quiz = Quiz.new(quiz_params)    
    if @quiz.save!      
      respond_to do |format|
        format.html { redirect_to quizzes_path, notice: "Quiz was successfully created." }
        format.turbo_stream { flash.now[:notice] = "Quiz was successfully created." }
      end
    else      
      flash[:error] = "Quiz not successfully created."      
      render :new
    end
  end  

  def update
    @quiz = Quiz.find(params[:id])    
    if @quiz.update(quiz_params)
      respond_to do |format|
        format.html { redirect_to quizzes_path, notice: "Quiz was successfully updated." }
        format.turbo_stream { flash.now[:notice] = "Quiz was successfully updated." }
      end     
    else              
      flash[:error] = "Quiz not successfully updated."      
      render :new
    end      
  end
 
  def destroy            
    Quiz.find(params[:id]).destroy
    respond_to do |format|
      format.html { redirect_to quiz_path(@quiz), notice: "Quiz was successfully deleted." }
      format.turbo_stream { flash.now[:notice] = "Quiz was successfully deleted." }
    end
  end


  private    

    def set_quiz
      @quiz = Quiz.find(params[:id])
    end

    def quiz_params      
      params.require(:quiz).permit(:name, :description)      
    end

end

app/views/quizzes/_form.html.erb
<%= form_for(@quiz, class: "form") do |f| %>    
    <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400 mt-6 ">    
        <tbody>  
            <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-100">

                <td class="px-6 py-4">
                    <label class="block text-gray-700 text-sm font-bold mb-2" for="name">Name</label>                            
                    <%= f.text_field :name, class:"fshadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline", required: "required", placeholder:"Name" %> 
                </td>

                <td class="px-6 py-4">
                    <label class="block text-gray-700 text-sm font-bold mb-2" for="description">Description</label>                                
                    <%= f.text_field :description, class:"fshadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline", required: "required", placeholder:"Description" %> 
                </td>

                <td class="px-6 py-4">   
                    <%= link_to "Cancel", quizzes_path, class: "font-medium px-3 py-2 font-semibold text-sm bg-gray-100 rounded-none shadow-sm" %>                                    
                    <button type="submit" class="font-medium px-3 py-2 font-semibold text-sm bg-red-500 rounded-none shadow-sm" style= "background-color: #08a6e8 ; color: white " >Save</button>            
                </td>

            </tr>        
        </tbody>
    </table>  
<%end%>

app/views/quizzes/_quiz.html.erb
<%= turbo_frame_tag quiz do %>
    <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400 mt-6 text-center" style="table-layout: fixed;">    
        <tbody>  
            <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-100">
                <td class="py-4"><%= link_to quiz.name.capitalize, quiz_path(quiz), data: { turbo_frame: "_top" } %></td>                
                <td class="py-4"><%= quiz.description%></td>                
                <td class="py-4 font-medium px-3 py-2 font-semibold text-sm text-red-500 rounded"><%= link_to  quiz.questions.count, quiz_path(quiz), data: { turbo_frame: "_top" } %></td>                      
                <td class="py-4"><%= link_to "Edit", edit_quiz_path(quiz), class: "font-medium px-3 py-2 font-semibold text-sm bg-red-500 rounded-none shadow-sm", style: "background-color: #08a6e8 ; color: white " %></td>                
                <td class="py-4"><%= button_to "Delete", quiz_path(quiz), method: :delete, form: { data: { turbo_frame: "_top", turbo_confirm: "Are you sure?" } }, class: "font-medium px-3 py-2 font-semibold text-sm bg-red-500 rounded-none shadow-sm", style: "background-color: #08a6e8 ; color: white "%></td>                
            </tr>        
        </tbody>  
    </table>  
<%end%> 

app/views/quizzes/create.turbo_stream.erb
<%= turbo_stream.prepend "quizzes", partial: "quizzes/quiz", locals: { quiz: @quiz } %>
<%= turbo_stream.update "new_quiz" %>

app/views/quizzes/destroy.turbo_stream.erb
<%= turbo_stream.remove @quiz %>

app/views/quizzes/edit.html.erb
<div class="mt-4 lg:p-12 p-4 grid grid-cols-1  gap-x-12 gap-y-4 relative z-20">
  
  <%= turbo_frame_tag @quiz do %>        
    <%= render "form", quote: @quiz %>          
  <% end %>

</div>
    
    


  

app/views/quizzes/index.html.erb
<%= turbo_stream_from "quizzes" %>

<div class="mt-1 lg:p-4 grid-cols-1    relative ">

  <%= link_to "New quiz",
    new_quiz_path,
    data: { turbo_frame: dom_id(Quiz.new) },
    class:"mt-4 relative font-medium px-2 py-2 font-semibold text-sm bg-sky-500 text-white rounded-none shadow-sm" 
  %>

</div>


<div class="lg:p-8  grid grid-cols-1  gap-x-12 gap-y-4 relative z-20">
                 
  <%= turbo_frame_tag Quiz.new %>
  
  <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400 mt-6 text-center" style="table-layout: fixed;">
    <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
      <tr>
          <th scope="col" class="px-6 py-3">Name</th>                                
          <th scope="col" class="px-6 py-3">Description</th>                                
          <th scope="col" class="px-6 py-3">Questions</th>                                  
          <th scope="col" class="px-6 py-3">Actions</th>                                    
          <th scope="col" class="px-6 py-3"></th>                  
          
      </tr>
    </thead>
  </table>
  
  
  <%= turbo_frame_tag "quizzes" do %>   
    <%= render @quizzes %>
  <%end%>
  
</div>

app/views/quizzes/new.html.erb
<div class="mt-4 lg:p-12 p-4 grid grid-cols-1  gap-x-12 gap-y-4 relative z-20">

  <%= link_to sanitize("&larr; Back to quizzes"), quizzes_path %>
      
  <%= turbo_frame_tag @quiz do %>
    <%= render "form", quiz: @quiz %>
  <%end%>

</div>

app/views/quizzes/show.html.erb
<div class="mt-1 lg:p-12 grid-cols-4 relative ">

  <h1><%= @quiz.name %></h1>    

  <br/>
  <a href="<%= quizzes_path%>" class="font-medium px-10 py-2 font-semibold text-sm bg-sky-500 text-white rounded-none shadow-sm">Back to quizzes</a>    
  

  <%= link_to "New Question",
      new_quiz_question_path(@quiz),
                  data: { turbo_frame: 'new_question' },
                  class: "font-medium px-2 py-2 font-semibold text-sm bg-sky-500 text-white rounded-none shadow-sm" %>

</div>


<div class="lg:p-12 grid grid-cols-1  gap-x-12 gap-y-4 relative z-20 ">

  <%= turbo_frame_tag Question.new %>
  
  <%= turbo_frame_tag "questions" do %>
    <%= render @questions, quiz: @quiz %>
  <% end %>

    
    
</div>

app/views/quizzes/update.turbo_stream.erb
<%= render_turbo_stream_flash_messages %>