config/routes.rb
Rails.application.routes.draw do
  
  root "home#welcome"

  devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'sign_up' }
  
  resources :users   
  
  resources :quizzes do
    resources :questions  do
      resources :options
    end
  end

  # API V1
  namespace :api, defaults: {format: :json}  do
    namespace :v1 do      
      post 'login', to: 'sessions#create'
      post 'logout', to: 'sessions#destroy'      
      resources :quizzes, only: [:index, :show]      
      resources :quiz_user_answers, only: [:create]      
    end
  end

  

  
end

app/views/shared/_flash_notice.html.erb
<% flash.each do |type, message| %>
  <div class="<%= flash_classes(type) %>">
    <%= message %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="flex flex-wrap items-center justify-between py-3 text-gray-700 bg-white container mx-auto lg:px-0 px-4 <%= nav_classes %>" data-controller="nav">
  <div class="flex items-center mr-6 flex-no-shrink">
     <%= link_to root_path, class:"link text-xl tracking-tight font-black" do %>
      <span class="sr-only">Assessment App</span>
      <%# Remove this logo and add your own %>
      <svg fill="none" class="w-9 h-9" height="512" viewBox="0 0 512 512" width="512" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><linearGradient id="a" gradientUnits="userSpaceOnUse" x1="56" x2="463" y1="46" y2="465"><stop offset="0" stop-color="#8038ed"/><stop offset="1" stop-color="#3a0092"/></linearGradient><path d="m0 0h512v512h-512z" fill="#fff"/><rect fill="url(#a)" height="512" rx="110" width="512"/><g stroke="#fff"><circle cx="190" cy="302" r="79.5" stroke-opacity=".9" stroke-width="25"/><circle cx="254" cy="377" r="34" stroke-opacity=".8" stroke-width="10"/><circle cx="282" cy="227" r="106" stroke-width="50"/></g></svg>
    <% end %>
  </div>
  <div class="block lg:hidden">
    <%# Mobile nav toggle %>
    <button class="flex items-center p-2 -mr-1 rounded-lg focus:bg-gray-100" data-action="click->nav#toggleMenu touch->nav#toggleMenu">
      <svg class="stroke-current text-gray-500 w-7 h-7" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><title>Menu</title><g fill="none"><path d="M4 6h16M4 12h8m-8 6h16" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path></g></svg>
    </button>
  </div>
  <div class="items-center w-full text-center lg:flex-1 lg:flex lg:text-left pt-2 lg:pt-0 hidden" data-nav-target="menu">
    <div class="lg:flex-grow">
      <%= link_to "Assessment App", "#", class: "p-3 hover:bg-gray-50 transition ease duration-300 rounded-lg text-center focus:bg-gray-100 lg:inline-block block" %>
    </div>
    <div class="items-center block w-full mt-2 text-center lg:flex lg:flex-row lg:flex-1 lg:mt-0 lg:text-left lg:justify-end">      

        <% if user_signed_in? %>
            <%= link_to "Users", users_path, class: "p-3 hover:bg-gray-50 transition ease duration-300 rounded-lg text-center focus:bg-gray-100 lg:inline-block block" %> | 

            <%= link_to "Tests", quizzes_path, class: "p-3 hover:bg-gray-50 transition ease duration-300 rounded-lg text-center focus:bg-gray-100 lg:inline-block block" %> | 

            
            <%= button_to "Log out", destroy_user_session_path, method: :delete, class:"p-3 hover:bg-gray-50 transition ease duration-300 rounded-lg text-center focus:bg-gray-100 lg:inline-block block" %>
        <% else %>

          <%= link_to "Sign in", new_user_session_path, class:"btn p-3 hover:bg-gray-50 transition ease duration-300 rounded-lg text-center focus:bg-gray-100 lg:inline-block block" %>          

        <% end %> 

    </div>
  </div>
</nav>